// <auto-generated />
using Assignment10._3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment10._3.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20260914170331_SeedCars")]
    partial class SeedCars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Assignment10._3.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Silver",
                            Make = "Honda",
                            Mileage = 42000,
                            Model = "Accord",
                            Price = 18500m,
                            VIN = "1HGCM82633A004352",
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue",
                            Make = "Ford",
                            Mileage = 27500,
                            Model = "F-150",
                            Price = 34900m,
                            VIN = "1FTFW1ET5EKF51234",
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Color = "White",
                            Make = "Tesla",
                            Mileage = 15200,
                            Model = "Model 3",
                            Price = 38750m,
                            VIN = "5YJ3E1EA7KF317890",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Color = "Red",
                            Make = "Toyota",
                            Mileage = 68000,
                            Model = "Prius",
                            Price = 14200m,
                            VIN = "JTDKN3DU0A0123456",
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black",
                            Make = "BMW",
                            Mileage = 51000,
                            Model = "328i",
                            Price = 21300m,
                            VIN = "WBA3A5C51CF256789",
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
