
// Real Timing Experiment: Generated by Copilot
var results = new List<(string algorithm, int n, long ms, long result)>();

Console.WriteLine("=== Climbing Stairs Timing Experiment ===\n");

// Test 1: Iterative O(n) - scales well
Console.WriteLine("Test 1: Iterative O(n)");
for (int n = 40; n <= 45; n++)
{
    var sw = System.Diagnostics.Stopwatch.StartNew();
    long result = ClimbStairs(n);
    sw.Stop();
    results.Add(("Iterative O(n)", n, sw.ElapsedMilliseconds, result));
    Console.WriteLine($"  n={n}: {sw.ElapsedMilliseconds}ms : {result}");
}

// Test 2: Recursive O(2^n) - only test small values!
Console.WriteLine("\nTest 2: Recursive O(2^n) : Exponential Growth!");
for (int n = 40; n <= 45; n++)
{
    var sw = System.Diagnostics.Stopwatch.StartNew();
    long result = ClimbStairsR(n);
    sw.Stop();
    results.Add(("Recursive O(2^n)", n, sw.ElapsedMilliseconds, result));
    Console.WriteLine($"  n={n}: {sw.ElapsedMilliseconds}ms : {result}");
}

// Test 3: Memoized O(n) - best of both worlds
Console.WriteLine("\nTest 3: Memoized O(n)");
for (int n = 40; n <= 45; n++)
{
    int[] vals = new int[n + 1];
    var sw = System.Diagnostics.Stopwatch.StartNew();
    long result = ClimbStairsM(n, vals);
    sw.Stop();
    results.Add(("Memoized O(n)", n, sw.ElapsedMilliseconds, result));
    Console.WriteLine($"  n={n}: {sw.ElapsedMilliseconds}ms : {result}");
}

Console.WriteLine("\n=== Summary ===");
var grouped = results.GroupBy(r => r.algorithm);
foreach (var group in grouped)
{
    Console.WriteLine($"\n{group.Key}:");
    var avgMs = group.Average(r => r.ms);
    Console.WriteLine($"  Average: {avgMs:F2}ms");
    Console.WriteLine($"  Range: {group.Min(r => r.ms)}-{group.Max(r => r.ms)}ms");
}



// Method definitions: created by me
static int ClimbStairs(int n)
{
    // n = 1
    if (n == 1)
    {
        return 1;
    }

    // n = 2
    int cur = 2, prev = 1;

    // n >= 3
    for (int i = 2; i < n; i++)
    {
        (cur, prev) = (cur + prev, cur);
    }

    return cur;
}

static int ClimbStairsR(int n)
{
    if(n == 1)
    {
        return 1;
    }

    if(n == 2)
    {
        return 2;
    }

    return ClimbStairsR(n - 1) + ClimbStairsR(n - 2);
}


static int ClimbStairsM(int n, int[] vals)
{
    if (vals[n] != 0)
    {
        return vals[n];
    }

    if (n == 1)
    {
        vals[1] = 1;
        return 1;
    }

    if (n == 2)
    {
        vals[2] = 2;
        return 2;
    }

    vals[n] = ClimbStairsM(n - 2, vals) + ClimbStairsM(n - 1, vals);
    return vals[n];
}