// testing suite generated by Copilot

Console.WriteLine("=== LeetCode 1603: Design Parking System Tests ===\n");

// Test 1: Basic functionality with multiple cars
Console.WriteLine("Test 1: Basic functionality");
ParkingSystem ps1 = new ParkingSystem(1, 1, 2);
Console.WriteLine($"AddCar(1): {ps1.AddCar(1)}"); // Expected: true
Console.WriteLine($"AddCar(2): {ps1.AddCar(2)}"); // Expected: true
Console.WriteLine($"AddCar(3): {ps1.AddCar(3)}"); // Expected: true
Console.WriteLine($"AddCar(3): {ps1.AddCar(3)}"); // Expected: true
Console.WriteLine($"AddCar(1): {ps1.AddCar(1)}"); // Expected: false (no big spots left)
Console.WriteLine($"AddCar(2): {ps1.AddCar(2)}"); // Expected: false (no medium spots left)
Console.WriteLine();

// Test 2: Single spot of each type
Console.WriteLine("Test 2: Single spot of each type");
ParkingSystem ps2 = new ParkingSystem(1, 1, 1);
Console.WriteLine($"AddCar(1): {ps2.AddCar(1)}"); // Expected: true
Console.WriteLine($"AddCar(2): {ps2.AddCar(2)}"); // Expected: true
Console.WriteLine($"AddCar(3): {ps2.AddCar(3)}"); // Expected: true
Console.WriteLine($"AddCar(1): {ps2.AddCar(1)}"); // Expected: false
Console.WriteLine($"AddCar(2): {ps2.AddCar(2)}"); // Expected: false
Console.WriteLine($"AddCar(3): {ps2.AddCar(3)}"); // Expected: false
Console.WriteLine();

// Test 3: Large parking lot
Console.WriteLine("Test 3: Large parking lot");
ParkingSystem ps3 = new ParkingSystem(4, 3, 2);
for (int i = 0; i < 4; i++)
    Console.WriteLine($"AddCar(1) #{i + 1}: {ps3.AddCar(1)}"); // Expected: 4 true values
Console.WriteLine($"AddCar(1) overflow: {ps3.AddCar(1)}"); // Expected: false

for (int i = 0; i < 3; i++)
    Console.WriteLine($"AddCar(2) #{i + 1}: {ps3.AddCar(2)}"); // Expected: 3 true values
Console.WriteLine($"AddCar(2) overflow: {ps3.AddCar(2)}"); // Expected: false

for (int i = 0; i < 2; i++)
    Console.WriteLine($"AddCar(3) #{i + 1}: {ps3.AddCar(3)}"); // Expected: 2 true values
Console.WriteLine($"AddCar(3) overflow: {ps3.AddCar(3)}"); // Expected: false
Console.WriteLine();

// Test 4: No parking spaces
Console.WriteLine("Test 4: No parking spaces available");
ParkingSystem ps4 = new ParkingSystem(0, 0, 0);
Console.WriteLine($"AddCar(1): {ps4.AddCar(1)}"); // Expected: false
Console.WriteLine($"AddCar(2): {ps4.AddCar(2)}"); // Expected: false
Console.WriteLine($"AddCar(3): {ps4.AddCar(3)}"); // Expected: false
Console.WriteLine();

// Test 5: Mixed operations
Console.WriteLine("Test 5: Mixed operations");
ParkingSystem ps5 = new ParkingSystem(2, 2, 1);
Console.WriteLine($"AddCar(3): {ps5.AddCar(3)}"); // Expected: true
Console.WriteLine($"AddCar(1): {ps5.AddCar(1)}"); // Expected: true
Console.WriteLine($"AddCar(2): {ps5.AddCar(2)}"); // Expected: true
Console.WriteLine($"AddCar(3): {ps5.AddCar(3)}"); // Expected: false
Console.WriteLine($"AddCar(1): {ps5.AddCar(1)}"); // Expected: true
Console.WriteLine($"AddCar(1): {ps5.AddCar(1)}"); // Expected: false
Console.WriteLine($"AddCar(2): {ps5.AddCar(2)}"); // Expected: true

Console.WriteLine("\n=== All tests completed ===");

public class ParkingSystem
{

    int[] _spacesAvailable = new int[4];

    public ParkingSystem(int big, int medium, int small)
    {
        _spacesAvailable[1] = big;
        _spacesAvailable[2] = medium;
        _spacesAvailable[3] = small;
    }

    public bool AddCar(int carType)
    {
        return _spacesAvailable[carType]-- > 0;
    }
}